<%
dDebug = false
dSQL = ""
bSubqueriesSupported = true
Set tables_data = (CreateDictionary())
Set field_labels = (CreateDictionary())
Set fieldToolTips = (CreateDictionary())
Set custom_labels = (CreateDictionary())
setArrElement custom_labels,"English",CreateDictionary()
Const FORMAT_NONE = ""
Const FORMAT_DATE_SHORT = "Short Date"
Const FORMAT_DATE_LONG = "Long Date"
Const FORMAT_DATE_TIME = "Datetime"
Const FORMAT_TIME = "Time"
Const FORMAT_CURRENCY = "Currency"
Const FORMAT_PERCENT = "Percent"
Const FORMAT_HYPERLINK = "Hyperlink"
Const FORMAT_EMAILHYPERLINK = "Email Hyperlink"
Const FORMAT_FILE_IMAGE = "File-based Image"
Const FORMAT_DATABASE_IMAGE = "Database Image"
Const FORMAT_DATABASE_FILE = "Database File"
Const FORMAT_FILE = "Document Download"
Const FORMAT_LOOKUP_WIZARD = "Lookup wizard"
Const FORMAT_PHONE_NUMBER = "Phone Number"
Const FORMAT_NUMBER = "Number"
Const FORMAT_HTML = "HTML"
Const FORMAT_CHECKBOX = "Checkbox"
Const FORMAT_MAP = "Map"
Const FORMAT_CUSTOM = "Custom"
Const FORMAT_AUDIO = "Audio file"
Const FORMAT_DATABASE_AUDIO = "Database audio"
Const FORMAT_VIDEO = "Video file"
Const FORMAT_DATABASE_VIDEO = "Database video"
Const EDIT_FORMAT_NONE = ""
Const EDIT_FORMAT_TEXT_FIELD = "Text field"
Const EDIT_FORMAT_TEXT_AREA = "Text area"
Const EDIT_FORMAT_PASSWORD = "Password"
Const EDIT_FORMAT_DATE = "Date"
Const EDIT_FORMAT_TIME = "Time"
Const EDIT_FORMAT_RADIO = "Radio button"
Const EDIT_FORMAT_CHECKBOX = "Checkbox"
Const EDIT_FORMAT_DATABASE_IMAGE = "Database image"
Const EDIT_FORMAT_DATABASE_FILE = "Database file"
Const EDIT_FORMAT_FILE = "Document upload"
Const EDIT_FORMAT_LOOKUP_WIZARD = "Lookup wizard"
Const EDIT_FORMAT_HIDDEN = "Hidden field"
Const EDIT_FORMAT_READONLY = "Readonly"
Const EDIT_DATE_SIMPLE = 0
Const EDIT_DATE_SIMPLE_DP = 11
Const EDIT_DATE_DD = 12
Const EDIT_DATE_DD_DP = 13
Const MODE_ADD = 0
Const MODE_EDIT = 1
Const MODE_SEARCH = 2
Const MODE_LIST = 3
Const MODE_PRINT = 4
Const MODE_VIEW = 5
Const MODE_INLINE_ADD = 6
Const MODE_INLINE_EDIT = 7
Const MODE_EXPORT = 8
Const LOGIN_HARDCODED = 0
Const LOGIN_TABLE = 1
Const SECURITY_NONE = -1
Const SECURITY_HARDCODED = 0
Const SECURITY_TABLE = 1
Const ADVSECURITY_ALL = 0
Const ADVSECURITY_VIEW_OWN = 1
Const ADVSECURITY_EDIT_OWN = 2
Const ADVSECURITY_NONE = 3
Const ACCESS_LEVEL_ADMIN = "Admin"
Const ACCESS_LEVEL_ADMINGROUP = "AdminGroup"
Const ACCESS_LEVEL_USER = "User"
Const ACCESS_LEVEL_GUEST = "Guest"
Const nDATABASE_MySQL = 0
Const nDATABASE_Oracle = 1
Const nDATABASE_MSSQLServer = 2
Const nDATABASE_Access = 3
Const nDATABASE_PostgreSQL = 4
Const nDATABASE_Informix = 5
Const nDATABASE_SQLite3 = 6
Const nDATABASE_DB2 = 7
Const ADD_SIMPLE = 0
Const ADD_INLINE = 1
Const ADD_ONTHEFLY = 2
Const ADD_MASTER = 3
Const ADD_POPUP = 4
Const EDIT_SIMPLE = 0
Const EDIT_INLINE = 1
Const EDIT_ONTHEFLY = 2
Const EDIT_POPUP = 3
Const titTABLE = 0
Const titVIEW = 1
Const titREPORT = 2
Const titCHART = 3
Const REPORT_STEPPED = 0
Const REPORT_BLOCK = 1
Const REPORT_OUTLINE = 2
Const REPORT_ALIGN = 3
Const REPORT_TABULAR = 6
Const TOTAL_NONE = -1
Const TOTAL_MAX = 0
Const TOTAL_AVG = 1
Const TOTAL_SUM = 3
Const TOTAL_MIN = 4
Const LIST_SIMPLE = 0
Const LIST_LOOKUP = 1
Const LIST_DETAILS = 3
Const LIST_AJAX = 4
Const RIGHTS_PAGE = 5
Const MEMBERS_PAGE = 6
Const DP_POPUP = 0
Const DP_INLINE = 1
Const DP_NONE = 2
Const SEARCH_SIMPLE = 0
Const SEARCH_LOAD_CONTROL = 1
Const LCT_DROPDOWN = 0
Const LCT_AJAX = 1
Const LCT_LIST = 2
Const LCT_CBLIST = 3
Const LT_LISTOFVALUES = 0
Const LT_LOOKUPTABLE = 1
Set globalSettings = (CreateDictionary())
setArrElement globalSettings,"nLoginMethod",0
setArrElement globalSettings,"dbType",2
wr_is_standalone = false
strLeftWrapper = "["
strRightWrapper = "]"
cLoginTable = ""
cUserNameField = ""
cPasswordField = ""
cUserGroupField = ""
cEmailField = ""
cUserNameFieldType = 200
cPasswordFieldType = 200
cEmailFieldType = 200
nDBType = 2
useAJAX = true
suggestAllContent = true
strLastSQL = ""
Set includes_js = (CreateDictionary())
Set includes_jsreq = (CreateDictionary())
Set includes_css = (CreateDictionary())
Set mlang_messages = (CreateDictionary())
Set mlang_charsets = (CreateDictionary())
Set tableCaptions = (CreateDictionary())
setArrElement tableCaptions,"English",CreateDictionary()
setArrElementN tableCaptions,CreateArray2("English","dbo_payment"),"Payment"
Set globalEvents = (CreateClass("class_GlobalEvents",0,Empty,Empty,Empty,Empty,Empty,Empty,Empty))
Set tableEvents = (CreateDictionary())
mlang_defaultlang = "English"
doAssignmentByRef conn,db_connect()
Set menuTablesArr = (CreateDictionary())
setArrElement menuTablesArr,asp_count(menuTablesArr),CreateDictionary3("shortTName","payment","dataSourceTName","payment","nType",0)
isGroupSecurity = false
%>
